### ISSUE TITLE
CLI: Expose a ledger to the invoke contract so we can get ledger info in contracts

### ISSUE THREAD

**Issue by paulbellamy** [stellar/soroban-cli#116]
Currently if you try to get ledger info in a contract called via `invoke`, it panics with "missing ledger info". We should inject a pseudo-ledger for the sandbox. It would be good if the ledger timestamp and sequence number incremented to more closely simulate a network.

Note: This should probably also apply to invoke's via `cli serve`

**Comment by leighmcculloch** [comment]
Ah yes we should set a ledger info. I think we probably need to set it, but then increment with each invoke. We can persist the value in the ledger.json maybe?
