### ISSUE TITLE
Include --instructions flag in `soroban contract deploy`

### ISSUE THREAD

**Issue by esteblock** [stellar/soroban-cli#1212]
### What problem does your feature solve?
Currently we need to increase the number of instructions to simulate in order to invoke a contract in Testnet or Mainnet.
We can do this adding the `--instructions` flag in `soroban contract invoke`

However, does not exist for ` soroban contract deploy`

### What would you like to see?
Include --instructions flag in `soroban contract deploy`

### What alternatives are there?
Deploy using javascript SDK

**Comment by tupui** [comment]
I think it needs to be added around here?

https://github.com/stellar/soroban-cli/blob/2ce9c35db3168c90b2eb95500bc0b7bf4bb2d30a/cmd/soroban-cli/src/commands/contract/deploy/asset.rs#L95

To do something like in `invoke`

https://github.com/stellar/soroban-cli/blob/2ce9c35db3168c90b2eb95500bc0b7bf4bb2d30a/cmd/soroban-cli/src/commands/contract/invoke.rs#L305

**Comment by leighmcculloch** [comment]
+1 We need a general set of flags that are included on any command that builds transactions.
