### ISSUE TITLE
Funding accounts errors with invalid uri error

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/soroban-cli#1251]
### What version are you using?

Broken in 38d865040dd1db59104675ac7dc38a7d1017943d (main)

### What did you do?

Generated a new key that also automatically gets funded:

```
$ soroban keys generate \
    --rpc-url https://soroban-testnet.stellar.org:443 \
    --network-passphrase 'Test SDF Network ; September 2015' \
    me
```

### What did you expect to see?

Successfully funded account, like it worked in ae5446f63ca8a275e61912019199254d598f3bd5 (v2.3.1).

### What did you see instead?

```
$ soroban keys generate \
    --rpc-url https://soroban-testnet.stellar.org:443 \
    --network-passphrase 'Test SDF Network ; September 2015' \
    me
2024-03-10T00:32:26.229192Z ERROR soroban_cli::commands::network: invalid uri character
2024-03-10T00:32:26.229550Z  WARN soroban_cli::commands::keys::generate: fund_address failed: Invalid URL https://friendbot.stellar.org/
```

**Comment by willemneal** [comment]
Can confirm locally! Looking into it! I changed the way that friendbot url is parsed from RPC because if using the local quickstart the friendbot url is hardcoded to use port 8000.
