### ISSUE TITLE
soroban-cli + contract init command

### ISSUE THREAD

**Issue by waldmatias** [stellar/soroban-cli#1262]
### What version are you using?
soroban 20.3.1 (ae5446f63ca8a275e61912019199254d598f3bd5)                                       in pwsh at 22:13:43
soroban-env 20.2.1 (18a10592853d9edf4e341b565b0b1638f95f0393)
soroban-env interface version 85899345920
stellar-xdr 20.1.0 (8b9d623ef40423a8462442b86997155f2c04d3a1)
xdr curr (b96148cd4acc372cc9af17b909ffe4b12c43ecb6)

### What did you do?
`soroban contract init hello_world`

### What did you expect to see?
Root level as well as hello world sample project generated. See attached: 
![win10_initcommand](https://github.com/stellar/soroban-cli/assets/13629804/4f22f451-673a-427b-b084-f2955dd2c25b)

### What did you see instead?
Just root level files are being generated.

**Comment by waldmatias** [comment]
BTW, this is happening on both Win10 and WSL2 Ubuntu, but seems to be happening on all others platforms.

**Comment by fnando** [comment]
This has been fixed by #1235 and is pending a release.

**Comment by janewang** [comment]
Thanks @fnando
