### ISSUE TITLE
CLI: The RPC interface does not follow the JSON-RPC 2.0 Specification

### ISSUE THREAD

**Issue by overcat** [stellar/soroban-cli#151]
### What version are you using?
80dfc96b3652eb232cceb893a0a451938c9f50a3

### What did you do?
```shell
soroban-cli serve

curl --location --request POST 'http://127.0.0.1:8080/api/v1/jsonrpc' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "id": 12134,
    "method": "getHealth"
}'
```

### What did you expect to see?
```json
{"jsonrpc":"2.0","id":12134,"result":{"status":"healthy"}}
```
### What did you see instead?

```json
{"jsonrpc":"2.0","id":12134,"error":{"code":-32601,"message":"unknownmethod","data":null}}
```

The following command works correctly.
```shell
curl --location --request POST 'http://127.0.0.1:8080/api/v1/jsonrpc' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "id": 12134,
    "method": "getHealth",
    "params": []
}'
```

Description in [JSON-RPC 2.0 Specification](https://www.jsonrpc.org/specification#request-object)
> params: A Structured value that holds the parameter values to be used during the invocation of the method. This member MAY be omitted.

**Comment by leighmcculloch** [comment]
cc @paulbellamy
