### ISSUE TITLE
CLI: Invoke and serve should be able to call token contract methods

### ISSUE THREAD

**Issue by paulbellamy** [stellar/soroban-cli#172]
Because we attempt to load the contract spec from the wasm in storage, for strval arg parsing, the token contract fails.
See: https://github.com/stellar/soroban-cli/blob/main/src/invoke.rs#L242

If the storage location indicates it is a token contract, soroban-cli should load the token spec from the soroban_token_spec crate, and use that to parse the args for token invocations.

Discovered while doing #81

**Comment by leighmcculloch** [comment]
The token contract has a spec here: https://github.com/stellar/rs-soroban-sdk/tree/main/soroban-token-spec. Maybe we should embed the .wasm build of it into the CLI?

**Comment by leighmcculloch** [comment]
It can be accessed another way, we don't actually need to build the .wasm.

It can be access with `Type::spec_xdr` for both implementations and types.
