### ISSUE TITLE
invoke arg with spaces produces xdr error

### ISSUE THREAD

**Issue by sreuland** [stellar/soroban-cli#187]
### What version are you using?

build of cli off `fb0f700d030970b9857645bdf87611c500255eef`

### What did you do?

`soroban invoke --wasm target/wasm32-unknown-unknown/release/soroban_hello_world_contract.wasm --fn hello --arg="como est" --rpc-server-url http://localhost:8000/soroban/rpc --secret-key <secret here> --network-passphrase "Standalone Network ; February 2017" --id <id here>`

### What did you expect to see?
success

### What did you see instead?
error: xdr processing error: failed to fill whole buffer

**Comment by leighmcculloch** [comment]
Spaces are not allowed in `Symbol`s. And the argument for the hello contract is a `Symbol`. `Symbol`s have an alphabet of `a-zA-Z0-9_`.

**Comment by sreuland** [comment]
I see, just curious, what would be alternate data type that end users could use if they wanted to enable this type of opaque character blob, is it the byte array type?

**Comment by leighmcculloch** [comment]
They'd pass the string as a bytes. The CLI should support string to bytes already I think.

**Comment by sreuland** [comment]
@leighmcculloch, thanks, related to error messaging, I was looking through existing issues, for something covering end user level error message on console output? as that's where it got confusing during this usage,  i.e. it's tough to know `error: xdr processing error: failed to fill whole buffer` was related to the `--arg` having an incorrect value.
