### ISSUE TITLE
Code completion does not work for `soroban` command

### ISSUE THREAD

**Issue by JakeUrban** [stellar/soroban-cli#244]
I tried adding the output of `soroban completion` to my zsh `fname` list, but when I used the `soroban` command it wasn't working. After going down an unnecessary rabbit hole, I realized it was working for `soroban-cli`. I'm assuming the completion script wasn't updated when the command name was changed.

**Comment by leighmcculloch** [comment]
I believe this was fixed in #239. The fix will be included in the next release that should go out today or tomorrow.

**Comment by leighmcculloch** [comment]
@JakeUrban would you be able to see if it resolves the issue you're experiencing? You can install the unreleased cli with the following command:

```
cargo install --locked --git https://github.com/stellar/soroban-cli soroban-cli
```

**Comment by JakeUrban** [comment]
It works 🎉

**Comment by JakeUrban** [comment]
I'll close this issue
