### ISSUE TITLE
CLI: Deploy a Contract via RPC

### ISSUE THREAD

**Issue by paulbellamy** [stellar/soroban-cli#41]
This is a high-level epic for the "deploy a contract to testnet/pubnet" user journey.

Meta question: Should this be a CLI tool, or a web UI like Laboratory?
  - @paulbellamy, I'd vote for a CLI tool as that will be easier to wrap and use from VSCode later.

We'll need:
- Generate a new wallet locally (for now)
- Print the wallet address so the dev can fund it (or get funding from friendbot)
- Build/sign/broadcast the contract deployment transaction
- Send/receive lumen transfers, so the dev can manage their balance

Nice-to-haves:
- Switch between multiple local wallet/identites
- Integrate with HW wallets like ledger/trezor so devs can be more secure
- Storage-management tools
  - For managing a contract storage. e.g. "fee-bump" to top up a storage location to prevent expiry (as per [cap-55](https://github.com/stellar/stellar-protocol/blob/master/core/cap-0055.md))

**Comment by leighmcculloch** [comment]
@paulbellamy It looks like this issue has pretty large surface area in terms of its user story. I suggest we narrow the user story so that it focuses on the deploy story specifically given that that's the scope of the title. I created a separate issue for a "faucet" story at https://github.com/stellar/soroban-cli/issues/142.

**Comment by leighmcculloch** [comment]
Today the `soroban-cli deploy` command deploys contracts to the local ledger file with the following command:
```
soroban-cli deploy [--ledger-file <FILE>] --id <CONTRACT_ID> --wasm <WASM>
```

I suggest this issue be to add additional options to the command that alter its behavior:
- `--account` – The account to submit a transaction with as source account. Required when deploying with a Horizon or RPC.
- `--horizon-url` – When provided the `deploy` command submits a transaction to Horizon.
- `--rpc-url` – When provided the `deploy` command submits a transaction to a soroban-rpc (or a soroban-cli serve).

The behavior would look like this:

1. `soroban-cli deploy --horizon-url <URL> --account <G...> --wasm <WASM>`
   - Make a HTTP request to Horizon to get the sequence number of the account.
   - Build a transaction with:
      - Source account set to the given account.
      - Sequence number set to the next sequence number for the source account.
      - One `INVOKE_HOST_FUNCTION` operation that calls the ed25519 contract deploy function and includes the given WASM. 
   - Prompt the user to enter the S secret key.
   - Sign the transaction with the S secret key.
   - Submit the transaction to the transaction submission endpoint of the Horizon URL.

2. `soroban-cli deploy --rpc-url <URL> --account <G...> --wasm <WASM>`
   - Make a HTTP request to the RPC server to get the sequence number of the account.
   - Build a transaction with:
      - Source account set to the given account.
      - Sequence number set to the next sequence number for the source account.
      - One `INVOKE_HOST_FUNCTION` operation that calls the ed25519 contract deploy function and includes the given WASM. 
   - Prompt the user to enter the S secret key.
   - Sign the transaction with the S secret key.
   - Submit the transaction to the `sendTransaction` endpoint of the RPC server.

_Note that in both flows an already created account is required, as we wouldn't want to encourage developers to create new accounts for every deploy that would make scaling already limited capacity faucets difficult on deployed test networks._

@paulbellamy @tomerweller Questions:

1. Does this align with plans in the RPC server?
1. What will be the preferred flow for deployment, via an RPC server or via Horizon?

**Comment by leighmcculloch** [comment]
I've renamed this issue to specify `RPC` specifically, and created a separate issue for `Horizon`: https://github.com/stellar/soroban-cli/issues/146.

**Comment by jcx120** [comment]
MVP for contract deploy for Meridian can be only via CLI (and not via Horizon #146, which can be post). Let's get one path functional before taking on others. Lmk if others disagree.
