### ISSUE TITLE
CLI: Map strkeys (e.g. G...) to FixedBinary<32>

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/soroban-cli#53]
People will naturally want to use Stellar's strkey format for keys as inputs to functions or arguments to things. We should map this to `FixedBinary<32>` or to some other type, so that people can continue to use those keys. ~Possibly now is the right time to finish implementing the `PublicKey` type that is still in the XDR.~

cc @paulbellamy @jayz22 @jonjove 

I'm revisiting this because of this question in Discord by @fsodano:
https://discord.com/channels/897514728459468821/966788672164855829/1003810451408306246

**Comment by paulbellamy** [comment]
Can we improve and re-use https://github.com/stellar/rs-stellar-strkey ?

**Comment by leighmcculloch** [comment]
Yes I think so.
