### ISSUE TITLE
CLI: Sandbox local http server for txn submission

### ISSUE THREAD

**Issue by paulbellamy** [stellar/soroban-cli#59]
### What problem does your feature solve?

A way to locally test web clients' txn submission

This follows on from #58 

### What would you like to see?

Local HTTP server should support txn submission against local sandbox

**Comment by paulbellamy** [comment]
Not: this is needed for https://github.com/stellar/js-stellar-sdk/issues/787 to be usable locally.

**Comment by leighmcculloch** [comment]
Currently the sandbox and the CLI has no notion of transactions as an input. I think a web application submitting a contract invocation should do see using a transaction submitted to Horizon. Those use cases probably require a running stellar-core, for which the quick start image is a more suitable target.

But I see your point, there's no way to test a web application that submits a Stellar tx.

I'm not sure how that sandbox would facilitate that. It explicitly has no transaction runtime and is unlikely to do so. Any transaction it accepts would be a mock implementation, ignoring most fields.

**Comment by leighmcculloch** [comment]
If we add an endpoint that does tx submission that ignores things like sequence numbers, preconditions, etc, then it could create a false sense of everything working if the transaction uses those things in meaningful ways. But that might be an edge case not worth solving for. 

For signature verification the CLI will need to gain account information like signatures at some point to test contracts that use account signers, so I guess it could implement it.

**Comment by leighmcculloch** [comment]
Will the CLI accept a tx, unpack it, error if it contains any non-contract invocations, and then invoke the contract specified, ignoring anything else in the tx like the source account, etc? Sgtm.
