### ISSUE TITLE
soroban-cli: add 'new' / 'init' command that creates a new project with the boilerplate

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/soroban-cli#656]
Developers would benefit from having a command they can run in soroban-cli that creates a new project with the dependencies and boilerplate already filled out, ready to go.

As evidenced by [this discussion](https://discord.com/channels/897514728459468821/1108412441932611684/1108412441932611684), it is easy to miss the simple things like including `#![no_std]` in the contract.

If developers have a command to run that creates a basic contract to start with, it'll help them get started without getting bogged down in the boilerplate basics.

The command could follow the behaviors of the `cargo new` and `cargo init` commands, although for the sake of reducing the surface area of our CLI, it would be nice if we could go with one or the other.

**Comment by elizabethengelman** [comment]
* First PR: https://github.com/stellar/soroban-tools/pull/1156
* I'll plan to add the following in a follow up PR:
    * `--frontend-template`
    * generate the possible example contracts to be included at runtime (https://github.com/stellar/soroban-tools/pull/1156#discussion_r1443144404https://github.com/stellar/soroban-tools/pull/1156#discussion_r1443144404)
