### ISSUE TITLE
CLI: Simulate and Invoke a contract on a network

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/soroban-cli#68]

**Comment by paulbellamy** [comment]
This is the first pass at soroban-rpc go, as described in https://excalidraw.com/#room=b2cc62ee24d336391d38,I1zzdEiGGHIsXZVmYp_mUw

So this will have some setup. The idea is to have a soroban-rpc go service which implements the jsonrpc api, backed by captive-core. That could be bundled with (or separately?) and launched by the `cli serve --futurenet` command (or equivalent).

**Comment by paulbellamy** [comment]
Issue to implement the soroban-rpc side of this is https://github.com/stellar/go/issues/4555

**Comment by sreuland** [comment]
@paulbellamy , wanted to confirm on expected outcome. Request is to add new http client invocations in CLI to a remote soroban-rpc compliant web service?  Does it also require adding the CLI commands to perform invoke/simulate operations as well or they are already plumbed in CLI? Does scope of this dev in CLI include a mocked soroban-rpc service?

**Comment by paulbellamy** [comment]
The commands already exist, but they only talk to sandbox for now. So we'll need to add a new backend. No mocked service for this, assume soroban-rpc is already implemented.
