### ISSUE TITLE
CLI: Generate shell autocompletion configuration

### ISSUE THREAD

**Issue by fdesjardins** [stellar/soroban-cli#69]
### What problem does your feature solve?

It would be nice if there were shell completions to help quickly enter commands and explore command options. Coming from Kubernetes/kubectl, I find autocompletion indispensable once you have a decent number of commands/subcommands/args in your CLI tool.

### What would you like to see?

Initially `bash` support would probably be sufficient, though `clap` completions are supported via https://crates.io/crates/clap_complete which supports common shells (bash, zsh, etc.).

### What alternatives are there?

- no completions
- manually generated completion scripts

Neither of these alternatives seem like good options to me.

I have a basic working implementation using `clap_complete` I can wrap up into a PR if this sounds like a desirable feature.

**Comment by leighmcculloch** [comment]
+1 Thanks for suggesting completions. This would be very helpful.
