### ISSUE TITLE
Create API Spec for RPC Node

### ISSUE THREAD

**Issue by tomerweller** [stellar/soroban-cli#78]
As discussed on Discord. This is to get everyone on the same page wrt the RPC API

Related to https://github.com/stellar/soroban-cli/issues/58

(not sure if it belongs in this repo or somewhere else)

**Comment by leighmcculloch** [comment]
> not sure if it belongs in this repo or somewhere else

Here is fine I think, given that the CLI will serve the same API, and we don't have another repo yet. Or rather, there is https://github.com/paulbellamy/rs-stellar-rpc, but that's the Rust version so probably not going to be it if we write it in Go.
