### ISSUE TITLE
CLI: Deploy native token contract

### ISSUE THREAD

**Issue by jonjove** [stellar/soroban-cli#81]
### What problem does your feature solve?

The deployment path for native contracts is different from WASM contracts.

### What would you like to see?

A nice interface to deploying the native token contract.

### What alternatives are there?

TODO

**Comment by leighmcculloch** [comment]
I think we should replace the term native in user facing things with "builtin". Native is an implementation detail that a developer actually doesn't need to know about. What they do need to know is that the contract is built into the runtime. 

I think we should avoid the term native and make it look like a convenience function to deploy a "built in" contract. Instead of providing a `--wasm file.wasm` it'd be `--builtin token`.

**Comment by paulbellamy** [comment]
Plus-one on builtin vs native. Native is not super informative for the dev.

I'm less opposed to a separate subcommand, though. For example, for [algorand ASAs](https://developer.algorand.org/docs/get-details/asa/#creating-an-asset), they do:
```
goal asset create \
  --creator <address> \
  --total 1000 \
  --unitname <unit-name> \
  --asseturl "https://path/to/my/asset/details" \
  --decimals 0 \
  -d data
```
Which is very clean and understandable what it is doing. It separates it out from "normal" contracts, as a special thing.

**Comment by tsachiherman** [comment]
so, on Algorand, the assets have their own set of transaction types.

**Comment by tsachiherman** [comment]
I believe that this was a mistake that we didn't catch up early.

**Comment by tsachiherman** [comment]
that is - it's ok to have a special transaction type for creating/destroying an asset. but the "regular" transfer transaction should be capable to be used for both assets and native coin ( xlm ).

**Comment by tsachiherman** [comment]
I think that for us, having a token-contract might be a bit misleading for the end-users ( compared to eth ). we do have the concept of assets - which aren't programmatic at all. this task is about creating a "virtual" asset that lives as a smart contract. I'm not sure what the best "name" for that, though. maybe smart asset in compared to non-smart assets ? ( "smart" as an indication of the smart contract ). problem is, it renders the native assets to be non-smart.

**Comment by paulbellamy** [comment]
Ok, this would be the same transaction type under-the-hood, just exposing it in a different way to the cli.

**Comment by paulbellamy** [comment]
This is blocked on @sisuresh changing how token contract deployment works.

**Comment by tsachiherman** [comment]
blocked by https://github.com/stellar/rs-soroban-env/issues/446

**Comment by tsachiherman** [comment]
unblocked now.

**Comment by sisuresh** [comment]
@paulbellamy This should be unblocked not that https://github.com/stellar/rs-soroban-env/commit/96d7a04761916f2d7ba312bea3a2d565b5e85416 was merged.
